spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: product-offers-producer
    consumer:
      client-id: product-offers-consumer
    streams:
      application-id: product-offers-stream
      replication-factor: 1
      auto-startup: false
  config:
    activate:
      on-profile: product-offers